routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('throttle:byIP20')
    ->group(function () {
        Route::middleware('guest')
            ->group(function () {
                Route::get('login', [\App\Http\Controllers\LoginController::class, 'showLoginForm'])->name('login');
                Route::post('login', [\App\Http\Controllers\LoginController::class, 'login']);

                //         Route::prefix('ref-mitra')
                //             ->name('referral-mitra.')
                //             ->group(function () {
                //                 // referral-mitra.link => /ref-mitra/{mitraReferral}
                //                 Route::get('/{mitraReferral}', [App\Http\Controllers\Member\ReferralLinkController::class, 'index'])->name('link');
                //                 // referral-mitra.register => /ref-mitra/{mitraReferral}/register
                //                 Route::post('/{mitraReferral}/register', [App\Http\Controllers\Member\ReferralLinkController::class, 'register'])->name('register');
                //             });

                //         // Route::get('activate/{username_activation}', [App\Http\Controllers\ActivationController::class, 'activate'])->name('activate');
            });

        include 'public.php';
    });

Route::middleware('throttle:byIP100')
    ->group(function () {
        Route::get('/', function () {
            if (Auth::check()) return redirect()->route('home');
            // return view('welcome');
            return redirect()->route('login');
        })->name('welcome');

        // Route::get('reload-captcha', function() {
        //     return captcha_src();
        // });

        

        Route::get('logout', [\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');
        Route::post('logout', [\App\Http\Controllers\LoginController::class, 'logout']);

        Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::get('/select-region', [App\Http\Controllers\RegionController::class, 'region'])->name('selectRegion');
        Route::get('/select-province', [App\Http\Controllers\RegionController::class, 'province'])->name('selectProvince');
        Route::get('/select-city', [App\Http\Controllers\RegionController::class, 'city'])->name('selectCity');
        Route::get('/select-district', [App\Http\Controllers\RegionController::class, 'district'])->name('selectDistrict');
        Route::get('/select-village', [App\Http\Controllers\RegionController::class, 'village'])->name('selectVillage');

        Route::prefix('{userDomain}')
            ->middleware('auth')
            ->group(function () {
                Route::get('/', function () {
                    return redirect()->route('dashboard');
                });
                // dashboard => /dashboard
                Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])
                    // ->middleware('auth.package')
                    ->name('dashboard');
                // password => /password
                Route::prefix('password')
                    ->name('password.')
                    ->group(function () {
                        Route::get('/', [App\Http\Controllers\PasswordController::class, 'passwordForm'])->name('index');
                        Route::post('/update', [App\Http\Controllers\PasswordController::class, 'updatePassword'])->name('update');
                    });

                // profile => /profile
                Route::prefix('profile')
                    ->name('profile.')
                    ->group(function () {
                        Route::get('/', [App\Http\Controllers\ProfileController::class, 'index'])->name('index');
                        // profile.edit => /profile/edit
                        Route::get('/edit', [\App\Http\Controllers\ProfileController::class, 'edit'])->name('edit');
                        // profile.update => /profile/update
                        Route::post('/update', [App\Http\Controllers\ProfileController::class, 'update'])->name('update');
                    });

                include 'main.php';
                include 'member.php';
                include 'mitra.php';
            });
    });

app/Models/BranchSale.php
<?php

namespace App\Models;

use App\Casts\FullDateCast;
use App\Casts\FullDatetimeCast;
use App\Casts\UppercaseCast;
use App\Models\Traits\ModelActiveTrait;
use App\Models\Traits\ModelCodeTrait;
use App\Models\Traits\ModelIDTrait;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class BranchSale extends Model
{
    use HasFactory, SoftDeletes;
    use ModelIDTrait, ModelCodeTrait, ModelActiveTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'code',
        'branch_id',
        'manager_id',
        'manager_position',
        'manager_type',
        'salesman_id',
        'salesman_position',
        'sale_date',
        'savings',
        'is_active',
        'salesman_note',
        'is_posted',
        'posted_at',
        'posted_by',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'code' => UppercaseCast::class,
        'sale_date' => FullDateCast::class,
        'is_active' => 'boolean',
        'is_posted' => 'boolean',
        'savings' => 'integer',
        'posted_at' => FullDatetimeCast::class,
    ];

    // boot
    public static function boot()
    {
        parent::boot();

        static::deleting(function ($branchSale) {
            foreach ($branchSale->products as $item) {
                $item->delete();
            }
        });
    }

    // relation
    public function products()
    {
        return $this->hasMany(BranchSalesProduct::class, 'branch_sale_id', 'id');
    }

    public function branch()
    {
        return $this->belongsTo(Branch::class, 'branch_id', 'id');
    }

    public function manager()
    {
        return $this->belongsTo(User::class, 'manager_id', 'id');
    }

    public function salesman()
    {
        return $this->belongsTo(User::class, 'salesman_id', 'id');
    }

    public function transfer()
    {
        return $this->hasOne(BranchTransferDetail::class, 'sale_id', 'id')
            ->whereHas('branchTransfer', function ($branchTransfer) {
                return $branchTransfer->whereIn('transfer_status', [PROCESS_STATUS_PENDING, PROCESS_STATUS_APPROVED]);
            });
    }

    // static
    public static function makeCode($saleDate): string
    {
        if (!is_int($saleDate)) $saleDate = strtotime($saleDate);
        $date = date('Ymd', $saleDate);
        $randCode = str_pad((string) mt_rand(10001, 999999), 6, '0', STR_PAD_LEFT);

        return "BS{$date}{$randCode}";
    }

    public static function applyDeletedCode(self &$branchSale): void
    {
        $code = $branchSale->code;

        $lastData = static::withTrashed()->where('code', 'like', "{$code}-%")->orderBy('id', 'desc')->first();
        $lastRange = 0;
        if (!empty($lastData)) {
            $codes = explode('-', $lastData->code);
            if (count($codes) > 1) {
                $lastRange = intval($codes[1]);
            }
        }
        $lastRange += 1;
        $branchSale->code = "{$code}-{$lastRange}";
    }

    // scope
    public function scopeByPosted(Builder $builder, bool $posted = null): Builder
    {
        return $builder->where('is_posted', '=', is_null($posted) ? false : $posted);
    }

    public function scopeByBranch(Builder $builder, $branch): Builder
    {
        $branchId = is_object($branch) ? $branch->id : $branch;

        return $builder->where('branch_id', '=', $branchId);
    }

    public function scopeByManager(Builder $builder, $manager): Builder
    {
        $managerId = is_object($manager) ? $manager->id : $manager;

        return $builder->where('manager_id', '=', $managerId);
    }

    public function scopeInBranches(Builder $builder, array $branchIds): Builder
    {
        return $builder->whereIn('branch_id', $branchIds);
    }

    public function scopeBySalesman(Builder $builder, $salesmanId): Builder
    {
        return $builder->where('salesman_id', '=', $salesmanId);
    }

    public function scopeByDate(Builder $builder, $date): Builder
    {
        $saleDate = ($date instanceof Carbon) ? $date->format('Y-m-d') : $date;

        return $builder->where('sale_date', '=', $saleDate);
    }

    public function scopeByBetweenDate(Builder $builder, $start, $end): Builder
    {
        $dateStart = ($start instanceof Carbon) ? $start->format('Y-m-d') : $start;
        $dateEnd = ($end instanceof Carbon) ? $end->format('Y-m-d') : $end;

        return $builder->whereBetween('sale_date', [$dateStart, $dateEnd]);
    }

    // accessor
    public function getProductQuantityAttribute()
    {
        $groups = $this->products->groupBy('product_id');
        $result = $groups->map(function ($items, $key) {
            return (object) [
                'product_id' => $key,
                'quantity' => $items->sum('product_qty')
            ];
        });

        return $result;
    }

    public function getSumQuantityProductAttribute()
    {
        return $this->products->sum('product_qty');
    }

    public function getSumQuantityBoxAttribute()
    {
        return $this->products->sum('qty_box');
    }

    public function getSumQuantityPcsAttribute()
    {
        return $this->products->sum('qty_pcs');
    }

    public function getSumTotalPriceAttribute()
    {
        return $this->products->sum('total_price');
    }

    public function getSumTotalProfitAttribute()
    {
        return $this->products->sum('total_profit');
    }

    public function getSumProfitCrewAttribute()
    {
        return $this->products->sum('profit_crew');
    }

    public function getSumFoundationAttribute()
    {
        return $this->products->sum('foundation');
    }

    public function getSalesNameAttribute()
    {
        return $this->salesman ? $this->salesman->name : null;
    }

    public function getSalesPositionAttribute()
    {
        return app('appStructure')->getDataById(true, $this->salesman_position ?? -1);
    }

    public function getSalesPositionCodeAttribute()
    {
        return $this->sales_position ? $this->sales_position->code : $this->salesman->internal_position_code;
    }

    public function getSalesPositionNameAttribute()
    {
        return $this->sales_position ? $this->sales_position->name : $this->salesman->internal_position_name;
    }

    public function getManagerNameAttribute()
    {
        return $this->manager ? $this->manager->name : null;
    }

    public function getBranchNameAttribute()
    {
        return $this->branch ? $this->branch->name : null;
    }

    public function getMgrPositionAttribute()
    {
        return app('appStructure')->getDataById(false, $this->manager_position ?? -1);
    }

    public function getMgrPositionCodeAttribute()
    {
        return $this->mgr_position ? $this->mgr_position->code : null;
    }

    public function getMgrPositionNameAttribute()
    {
        return $this->mgr_position ? $this->mgr_position->name : null;
    }

    public function getIsTransferredAttribute()
    {
        return !empty($this->transfer);
    }
}

resources/views/main/reports/global/pdf/manager-detail.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $filename }}</title>
    <style>
        @page {
            margin: 10pt 10pt 20pt;
        }
        body {
            margin: 10pt 10pt 20pt;
        }
        * {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 10pt;
        }
        .header-title {
            font-size: 16pt;
        }
        .header-sub-title {
            font-size: 12pt;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
        }
        .table th,
        .table td {
            padding: 2pt 4pt;
        }
        .table th.space,
        .table td.space {
            padding: 5pt;
        }
        .table thead th {
            font-weight: bold;
            text-align: center;
            vertical-align: middle;
        }
        .table tbody td {
            vertical-align: top;
        }
        .cell-number {
            text-align: right;
        }
        .cell-border {
            border: 1px solid #212529;
        }
        .small {
            font-size: 8pt;
        }
        .info-upline {
            font-size: 9pt;
            font-style: italic;
        }
    </style>
</head>
<body>
    @php
        $tanggal = formatFullDate($startDate);
        if ($startDate->format('Y-m-d') != $endDate->format('Y-m-d')) {
            $tanggal .= ' s/d ' . formatFullDate($endDate);
        }
        $spanHeader = !empty($branch) ? 8 : 9;
    @endphp
    <table class="table">
        <thead>
            <tr>
                <th class="header-title" colspan="{{ $spanHeader }}">{{ $titleHeader }}</th>
            </tr>
            <tr>
                <th class="header-sub-title" colspan="{{ $spanHeader }}">{{ $tanggal }}</th>
            </tr>
            @if (!empty($branch))
            <tr>
                <th class="header-sub-title" colspan="{{ $spanHeader }}">Cabang {{ $branch->name }}</th>
            </tr>
            @endif
            @if (!empty($manager))
            <tr>
                <th class="header-sub-title" colspan="{{ $spanHeader }}">Manager: {{ $manager->name }}</th>
            </tr>
            @endif
            <tr>
                <th colspan="{{ $spanHeader }}" class="space"></th>
            </tr>
            <tr>
                <th rowspan="2" class="cell-border">No</th>
                <th rowspan="2" class="cell-border">Nama</th>
                <th rowspan="2" class="cell-border">Posisi</th>
                <th rowspan="2" class="cell-border">Upline</th>
                @if (empty($branch))
                    <th rowspan="2" class="cell-border">Cabang</th>
                @endif
                <th rowspan="2" class="cell-border">Product</th>
                <th colspan="2" class="cell-border">QTY</th>
                <th rowspan="2" class="cell-border">
                    <div>Total Omzet</div>
                    <div class="small">(Rp)</div>
                </th>
            </tr>
            <tr>
                <th class="cell-border">Box</th>
                <th class="cell-border">Pcs</th>
            </tr>
        </thead>
        <tbody>
            @php
                $noUrut = 1;
                $teamId = 0;
            @endphp
            @foreach ($rows->groupBy('team_id')->sortBy('team_name') as $team_id => $teams)
                @php
                    $branchId = 0;
                    $team = $teams->first();
                    $teamName = $team->team_name;
                    $positionName = $team->position_name;
                    $uplineInfo = "<div>{$team->upline_name}</div><div class=\"info-upline\">{$team->upline_position_name}</div>";
                @endphp
                @foreach ($teams->groupBy('branch_id')->sortBy('branch_name') as $branch_id => $branches)
                    @php
                        $branchName = $branches->first()->branch_name;
                    @endphp
                    @foreach ($branches->groupBy('product_id')->sortBy('product_name') as $products)
                        <tr>
                            <td class="cell-number cell-border">{{ ($teamId != $team_id) ? "{$noUrut}." : '' }}</td>
                            <td class="cell-border">{{ ($teamId != $team_id) ? $teamName : '' }}</td>
                            <td class="cell-border">{{ ($teamId != $team_id) ? $positionName : '' }}</td>
                            <td class="cell-border">{!! ($teamId != $team_id) ? $uplineInfo : '' !!}</td>
                            @if (empty($branch))
                                <td class="cell-border">{{ ($branchId != $branch_id) ? $branchName : '' }}</td>
                            @endif
                            <td class="cell-border">{{ $products->first()->product_name }}</td>
                            <td class="cell-number cell-border">@formatNumber($products->sum('qty_box'), 0)</td>
                            <td class="cell-number cell-border">@formatNumber($products->sum('qty_pcs'), 0)</td>
                            <td class="cell-number cell-border">@formatNumber($products->sum('total_omzet'), 0)</td>
                        </tr>
                    @endforeach
                    @php
                        $branchId = $branch_id;
                    @endphp
                @endforeach
                @php
                    $teamId = $team_id;
                    $noUrut++;
                @endphp
            @endforeach
        </tbody>
    </table>

    {{-- page number --}}
    <script type="text/php">
        if (isset($pdf)) {
            $text = "- {PAGE_NUM} -";
            $size = 10;
            $font = "{{ config('dompdf.defines.default_font') }}";
            $width = $fontMetrics->get_text_width($text, $font, $size) / 4;
            $x = ($pdf->get_width() - $width) / 2;
            $y = $pdf->get_height() - 20;
            $pdf->page_text($x, $y, $text, $font, $size);
        }
    </script>
</body>
</html>

resources/views/main/reports/global/pdf/manager.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $filename }}</title>
    <style>
        @page {
            margin: 10pt 10pt 20pt;
        }
        body {
            margin: 10pt 10pt 20pt;
        }
        * {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 10pt;
        }
        .header-title {
            font-size: 16pt;
        }
        .header-sub-title {
            font-size: 12pt;
        }
        .table {
            width: 100%;
            border-collapse: collapse;
        }
        .table th,
        .table td {
            padding: 2pt 4pt;
        }
        .table th.space,
        .table td.space {
            padding: 5pt;
        }
        .table thead th {
            text-align: center;
            vertical-align: middle;
        }
        .table tbody td {
            vertical-align: top;
        }
        .cell-bold {
            font-weight: bold;
        }
        .cell-right {
            text-align: right;
        }
        .cell-border {
            border: 1px solid #212529;
        }
        .small {
            font-size: 8pt;
        }
    </style>
</head>
<body>
    @php
        $tanggal = formatFullDate($startDate);
        if ($startDate->format('Y-m-d') != $endDate->format('Y-m-d')) {
            $tanggal .= ' s/d ' . formatFullDate($endDate);
        }
        $spanHeader = 7;
        if (!empty($branch)) $spanHeader -= 1;
        if (!empty($manager)) $spanHeader -= 1;
    @endphp
    <table class="table">
        <thead class="cell-bold">
            <tr>
                <th class="header-title" colspan="{{ $spanHeader }}">{{ $titleHeader }}</th>
            </tr>
            <tr>
                <th class="header-sub-title" colspan="{{ $spanHeader }}">{{ $tanggal }}</th>
            </tr>
            @if (!empty($branch))
            <tr>
                <th class="header-sub-title" colspan="{{ $spanHeader }}">Cabang: {{ $branch->name }}</th>
            </tr>
            @endif
            @if (!empty($manager))
            <tr>
                <th class="header-sub-title" colspan="{{ $spanHeader }}">Manager: {{ $manager->name }}</th>
            </tr>
            @endif
            <tr>
                <th colspan="{{ $spanHeader }}" class="space"></th>
            </tr>
            <tr>
                <th rowspan="2" class="cell-border">No</th>
                @if (empty($manager))
                    <th rowspan="2" class="cell-border">Manager</th>
                @endif
                @if (empty($branch))
                    <th rowspan="2" class="cell-border">Cabang</th>
                @endif
                <th rowspan="2" class="cell-border">Product</th>
                <th colspan="2" class="cell-border">QTY</th>
                <th rowspan="2" class="cell-border">
                    <div>Total Omzet</div>
                    <div class="small">(Rp)</div>
                </th>
            </tr>
            <tr>
                <th class="cell-border">Box</th>
                <th class="cell-border">Pcs</th>
            </tr>
        </thead>
        <tbody>
            @php
                $noUrut = 1;
                $totalBox = 0;
                $totalPcs = 0;
                $totalOmzet = 0;
            @endphp
            @foreach ($rows as $row)
                <tr>
                    <td class="cell-right cell-border">{{ $noUrut++ }}.</td>
                    @if (empty($manager))
                        <td class="cell-border">{{ $row->manager_name }} ({{ $row->username }})</td>
                    @endif
                    @if (empty($branch))
                        <td class="cell-border">{{ $row->branch_name }}</td>
                    @endif
                    @php
                        $box = intval($row->qty_box);
                        $pcs = intval($row->qty_pcs);
                        $omzet = intval($row->total_omzet);
                        $totalBox += $box;
                        $totalPcs += $pcs;
                        $totalOmzet += $omzet;
                    @endphp

                    <td class="cell-border">{{ $row->product_name }}</td>
                    <td class="cell-right cell-border">@formatNumber($box, 0)</td>
                    <td class="cell-right cell-border">@formatNumber($pcs, 0)</td>
                    <td class="cell-right cell-border">@formatNumber($omzet, 0)</td>
                </tr>
            @endforeach
            {{-- @foreach ($rows->groupBy('manager_id')->sortBy('manager_name') as $managers)
                @php
                    $managerName = $managers->first()->manager_name;
                    $branchesManager = $managers->groupBy('branch_id')->values();
                    $managerSpanned = false;
                @endphp
                @foreach ($branchesManager->sortBy('branch_name') as $branches)
                    @php
                        $branchName = $branches->first()->branch_name;
                        $branchProducts = $branches->groupBy('product_id')->values();
                        $branchSpanned = false;
                    @endphp
                    @foreach ($branchProducts->sortBy('product_name') as $products)
                        <tr>
                            <td class="cell-right cell-border">{{ ($managerSpanned !== true) ? $noUrut . '.' : '' }}</td>
                            @if (empty($manager))
                                <td class="cell-border">{{ ($managerSpanned !== true) ? $managerName : '' }}</td>
                            @endif
                            @php
                                $managerSpanned = true;
                            @endphp
                            @if (empty($branch))
                                <td class="cell-border">{{ ($branchSpanned !== true) ? $branchName : '' }}</td>
                            @endif
                            @php
                                $branchSpanned = true;
                            @endphp
                            @php
                                $box = $products->sum('qty_box');
                                $pcs = $products->sum('qty_pcs');
                                $omzet = $products->sum('total_omzet');
                                $totalBox += $box;
                                $totalPcs += $pcs;
                                $totalOmzet += $omzet;
                            @endphp

                            <td class="cell-border">{{ $products->first()->product_name }}</td>
                            <td class="cell-right cell-border">@formatNumber($box, 0)</td>
                            <td class="cell-right cell-border">@formatNumber($pcs, 0)</td>
                            <td class="cell-right cell-border">@formatNumber($omzet, 0)</td>
                        </tr>
                    @endforeach
                @endforeach
                @php
                    $noUrut++;
                @endphp
            @endforeach --}}
        </tbody>
        <tfoot>
            @php
                $footerSpan = 4;
                if (!empty($branch)) $footerSpan -= 1;
                if (!empty($manager)) $footerSpan -= 1;
            @endphp
            <tr>
                <td class="cell-border cell-right cell-bold" colspan="{{ $footerSpan }}">Total</td>
                <td class="cell-border cell-right cell-bold">@formatNumber($totalBox, 0)</td>
                <td class="cell-border cell-right cell-bold">@formatNumber($totalPcs, 0)</td>
                <td class="cell-border cell-right cell-bold">@formatNumber($totalOmzet, 0)</td>
            </tr>
        </tfoot>
    </table>

    {{-- page number --}}
    <script type="text/php">
        if (isset($pdf)) {
            $text = "- {PAGE_NUM} -";
            $size = 8;
            $font = "{{ config('dompdf.defines.default_font') }}";
            $width = $fontMetrics->get_text_width($text, $font, $size) / 4;
            $x = ($pdf->get_width() - $width) / 2;
            $y = $pdf->get_height() - 20;
            $pdf->page_text($x, $y, $text, $font, $size);
        }
    </script>
</body>
</html>