routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::middleware('throttle:byIP20')
    ->group(function () {
        Route::middleware('guest')
            ->group(function () {
                Route::get('login', [\App\Http\Controllers\LoginController::class, 'showLoginForm'])->name('login');
                Route::post('login', [\App\Http\Controllers\LoginController::class, 'login']);

                //         Route::prefix('ref-mitra')
                //             ->name('referral-mitra.')
                //             ->group(function () {
                //                 // referral-mitra.link => /ref-mitra/{mitraReferral}
                //                 Route::get('/{mitraReferral}', [App\Http\Controllers\Member\ReferralLinkController::class, 'index'])->name('link');
                //                 // referral-mitra.register => /ref-mitra/{mitraReferral}/register
                //                 Route::post('/{mitraReferral}/register', [App\Http\Controllers\Member\ReferralLinkController::class, 'register'])->name('register');
                //             });

                //         // Route::get('activate/{username_activation}', [App\Http\Controllers\ActivationController::class, 'activate'])->name('activate');
            });

        include 'public.php';
    });

Route::middleware('throttle:byIP100')
    ->group(function () {
        Route::get('/', function () {
            if (Auth::check()) return redirect()->route('home');
            // return view('welcome');
            return redirect()->route('login');
        })->name('welcome');

        // Route::get('reload-captcha', function() {
        //     return captcha_src();
        // });

        

        Route::get('logout', [\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');
        Route::post('logout', [\App\Http\Controllers\LoginController::class, 'logout']);

        Route::get('/home', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

        Route::get('/select-region', [App\Http\Controllers\RegionController::class, 'region'])->name('selectRegion');
        Route::get('/select-province', [App\Http\Controllers\RegionController::class, 'province'])->name('selectProvince');
        Route::get('/select-city', [App\Http\Controllers\RegionController::class, 'city'])->name('selectCity');
        Route::get('/select-district', [App\Http\Controllers\RegionController::class, 'district'])->name('selectDistrict');
        Route::get('/select-village', [App\Http\Controllers\RegionController::class, 'village'])->name('selectVillage');

        Route::prefix('{userDomain}')
            ->middleware('auth')
            ->group(function () {
                Route::get('/', function () {
                    return redirect()->route('dashboard');
                });
                // dashboard => /dashboard
                Route::get('/dashboard', [App\Http\Controllers\DashboardController::class, 'index'])
                    // ->middleware('auth.package')
                    ->name('dashboard');
                // password => /password
                Route::prefix('password')
                    ->name('password.')
                    ->group(function () {
                        Route::get('/', [App\Http\Controllers\PasswordController::class, 'passwordForm'])->name('index');
                        Route::post('/update', [App\Http\Controllers\PasswordController::class, 'updatePassword'])->name('update');
                    });

                // profile => /profile
                Route::prefix('profile')
                    ->name('profile.')
                    ->group(function () {
                        Route::get('/', [App\Http\Controllers\ProfileController::class, 'index'])->name('index');
                        // profile.edit => /profile/edit
                        Route::get('/edit', [\App\Http\Controllers\ProfileController::class, 'edit'])->name('edit');
                        // profile.update => /profile/update
                        Route::post('/update', [App\Http\Controllers\ProfileController::class, 'update'])->name('update');
                    });

                include 'main.php';
                include 'member.php';
                include 'mitra.php';
            });
    });

app/Models/Product.php
<?php

namespace App\Models;

// use App\Casts\FloatCast;
use App\Casts\HtmlStringCast;
use App\Casts\UppercaseCast;
use App\Models\Traits\ModelActiveTrait;
use App\Models\Traits\ModelCodeTrait;
use App\Models\Traits\ModelIDTrait;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Arr;

class Product extends Model
{
    use HasFactory;
    use ModelIDTrait, ModelCodeTrait, ModelActiveTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'code',
        'product_category_id',
        'name',
        'satuan',
        'isi',
        'satuan_isi',
        'notes',
        'description',
        'harga_a', // harga produk
        'harga_b', // blum digunakan
        'harga_c', // blum digunakan
        'harga_d', // blum digunakan
        // 'eceran_a', // harga eceran jika satuan box
        'eceran_a', // belum digunakan
        'eceran_b', // blum digunakan
        'eceran_c', // blum digunakan
        'eceran_d', // blum digunakan
        'image',
        'is_active',
        'active_at',
        'is_publish',
        'self_point',
        'upline_point',
        'bonus_sponsor',
        'bonus_sponsor_ro',
        'bonus_cashback',
        'bonus_cashback_condition',
        'bonus_cashback_ro',
        'bonus_cashback_ro_condition',
        'package_range',
        'package_type',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'code' => UppercaseCast::class,
        'satuan' => 'integer',
        'isi' => 'integer',
        'active_at' => 'datetime',
        'satuan_isi' => 'integer',
        'harga_a' => 'integer',
        'harga_b' => 'integer',
        'harga_c' => 'integer',
        'harga_d' => 'integer',
        'eceran_a' => 'integer',
        'eceran_b' => 'integer',
        'eceran_c' => 'integer',
        'eceran_d' => 'integer',
        'self_point' => 'integer',
        'upline_point' => 'integer',
        'is_active' => 'boolean',
        'is_publish' => 'boolean',
        'notes' => HtmlStringCast::class,
        'description' => HtmlStringCast::class,
        'bonus_sponsor' => 'integer',
        'bonus_sponsor_ro' => 'integer',
        'bonus_cashback_ro' => 'integer',
        'package_range' => 'integer',
        'package_type' => 'integer',
    ];

    public const IMAGE_DISK = 'product';
    public const IMAGE_ASSET = 'images/uploads/products/';

    // relation
    public function category()
    {
        return $this->belongsTo(ProductCategory::class, 'product_category_id', 'id');
    }

    public function productBranch()
    {
        return $this->hasMany(BranchProduct::class, 'product_id', 'id');
    }

    public function prices()
    {
        return $this->hasMany(ProductPrice::class, 'product_id', 'id')->whereHas('zone');
    }

    public function mitraDiscount()
    {
        return $this->hasMany(ProductDiscount::class, 'product_id', 'id')->byMitraType(MITRA_TYPE_AGENT);
    }

    public function mitraReward()
    {
        return $this->hasMany(ProductReward::class, 'product_id', 'id');
    }

    // scope
    public function scopeAvailableProductBranch(Builder $builder, Branch $branch, $currentProductId = null): Builder
    {
        $branchId = $branch ? $branch->id : 0;

        return $builder->where(function (Builder $b) use ($branchId, $currentProductId) {
            $b->whereDoesntHave('productBranch', function (Builder $x) use ($branchId) {
                $x->where('branch_id', '=', $branchId);
            });
            if (!is_null($currentProductId)) $b->orWhere('id', '=', $currentProductId);
        });
    }

    public function scopeByCategory(Builder $builder, $category): Builder
    {
        $categoryId = is_object($category) ? $category->id : ($category ?? -1);
        return ($categoryId <= 0) ? $builder : $builder->where('product_category_id', '=', $categoryId);
    }

    public function scopeByPublished(Builder $builder, bool $publish = null): Builder
    {
        return $builder->where('is_publish', '=', is_null($publish) ? true : $publish);
    }

    public function scopeByHasPrice(Builder $builder, string $field = null): Builder
    {
        $field = $field ?? 'harga_a';

        return $builder->where($field, '>', 0);
    }

    public function scopeByPackageRange(Builder $builder, int $range): Builder
    {
        return $builder->where('package_range', '=', $range);
    }

    // static
    public static function lastPackageRange()
    {
        return static::query()->max('package_range');
    }
    // static:end

    // accessor
    public function getImageUrlAttribute()
    {
        return asset(static::IMAGE_ASSET . $this->image);
    }

    public function getCategoryNameAttribute()
    {
        return $this->category ? $this->category->name : null;
    }

    public function getKomisiAttribute()
    {
        $setting = app('neo')->settingBonusSell();

        return optional($setting)->percent ?? 0;
    }

    public function getProductUnitAttribute()
    {
        return strtoupper(Arr::get(PRODUCT_UNITS, $this->satuan, ''));
    }

    public function getVolumeProductUnitAttribute()
    {
        if ($this->satuan == PRODUCT_UNIT_BOX) {
            return strtoupper(Arr::get(PRODUCT_UNITS, $this->satuan_isi, ''));
        }

        return null;
    }

    public function getPackageNameAttribute()
    {
        return config('app.name') . $this->package_range;
    }

    public function getPackageTypeNameAttribute()
    {
        $default = Arr::get(MITRA_LEVELS, MITRA_LEVEL_RESELLER);

        return Arr::get(MITRA_LEVELS, $this->package_type, $default);
    }

    // public method
    public function zonePrice(int $zone)
    {
        if ($zone == ZONE_WEST) return $this->harga_a;
        if ($zone == ZONE_EAST) return $this->harga_b;

        return 0;
    }

    public function eceranZonePrice(int $zone)
    {
        if ($zone == ZONE_WEST) return ($this->satuan == PRODUCT_UNIT_BOX) ? $this->eceran_a : 0;
        if ($zone == ZONE_EAST) return ($this->satuan == PRODUCT_UNIT_BOX) ? $this->eceran_b : 0;

        return 0;
    }

    public function zoneMitraPrice(int $zone)
    {
        if ($zone == ZONE_WEST) return $this->harga_a;
        if ($zone == ZONE_EAST) return $this->harga_b;

        return 0;
    }

    public function zoneMitraPriceList(): array
    {
        $list = [$this->zoneMitraPrice(ZONE_WEST), $this->zoneMitraPrice(ZONE_EAST)];

        $min = min($list);
        $max = max($list);

        return ($min != $max) ? [$min, $max] : [$min];
    }

    public function zonePriceV2(int $zone)
    {
        $price = optional($this->prices->where('zone_id', '=', $zone)->first());
        return $price->normal_price ?? 0;
    }

    public function eceranZonePriceV2(int $zone)
    {
        $price = optional($this->prices->where('zone_id', '=', $zone)->first());

        return ($this->satuan == PRODUCT_UNIT_BOX) ? ($price->normal_retail_price ?? 0) : 0;
    }

    public function zoneMitraPriceV2(int $zone, int $qty = null)
    {
        $price = optional($this->prices->where('zone_id', '=', $zone)->first());
        $result = $price->mitra_price ?? 0;
        if (($result > 0) && !is_null($qty) && ($qty > 0)) {
            $productDiscount = $this->mitraDiscount->where('min_qty', '<=', $qty)->sortBy(['min_qty', 'desc'])->first();
            if (!empty($productDiscount)) {
                $result = $result - $productDiscount->discount;
            }
        }

        return $result;
    }

    public function zoneMitraPromoPriceV2(int $zone, int $qty = null)
    {
        $price = optional($this->prices->where('zone_id', '=', $zone)->first());
        $result = $price->mitra_promo_price ?? 0;
        if (($result > 0) && !is_null($qty) && ($qty > 0)) {
            $productDiscount = $this->mitraDiscount->where('min_qty', '<=', $qty)->sortBy(['min_qty', 'desc'])->first();
            if (!empty($productDiscount)) {
                $result = $result - $productDiscount->discount;
            }
        }

        return $result;
    }

    public function zoneMitraPriceV2List(): array
    {
        if ($this->prices->isEmpty()) return [0];

        $min = $this->prices->min('mitra_price');
        $max = $this->prices->max('mitra_price');

        return ($min != $max) ? [$min, $max] : [$min];
    }
}

app/Http/Controllers/Main/Products/BonusController.php
<?php

namespace App\Http\Controllers\Main\Products;

use App\Helpers\Neo;
use App\Http\Controllers\Controller;
use App\Models\ProductPrice;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;

class BonusController extends Controller
{
    private Neo $neo;

    public function __construct()
    {
        $this->neo = app('neo');
    }

    public function index(Request $request)
    {
        $product = $request->product;

        return view('main.products.bonus.index', [
            'product' => $product,
            'windowTitle' => 'Daftar Diskon Produk',
            'breadcrumbs' => ['Master', 'Produk', 'Bonus']
        ]);
    }

    private function validateInput(array &$values, ProductPrice $productPrice)
    {
        $values = array_merge([
            'zone_id' => $productPrice->zone_id,
            'product_id' => $productPrice->product_id,
            'normal_price' => $productPrice->normal_price,
            'normal_retail_price' => $productPrice->normal_retail_price,
            'mitra_price' => $productPrice->mitra_price,
            'mitra_retail_price' => $productPrice->mitra_retail_price,
        ], $values);

        $validator = Validator::make($values, [
            'mitra_basic_bonus' => 'required|integer|min:0',
            'mitra_premium_bonus' => 'required|integer|min:0',
            'distributor_bonus' => 'required|integer|min:0',
        ]);

        $result = ['status' => true, 'message' => ''];

        if ($validator->fails()) {
            $result['status'] = false;
            $result['message'] = $this->validationMessages($validator);
        }

        return $result;
    }

    public function edit(Request $request)
    {
        $product = $request->product;
        $zone = $request->zone;
        $zoneId = $zone->id;
        $price = $product->prices()->where('zone_id', '=', $zoneId)->first();

        if (empty($price)) return ajaxError('Harga produk belum ditentukan.', 404);

        return view('main.products.bonus.form', [
            'product' => $product,
            'data' => $price,
            'zone' => $zone,
            'postUrl' => route('main.master.product.bonus.update', ['product' => $product->id, 'zone' => $zoneId]),
            'modalHeader' => 'Edit Bonus Produk',
        ]);
    }

    public function update(Request $request)
    {
        $product = $request->product;
        $zone = $request->zone;
        $zoneId = $zone->id;
        $productPrice = $product->prices()->where('zone_id', '=', $zoneId)->first();

        $responCode = 200;
        $responText = route('main.master.product.bonus.index', ['product' => $product->id]);

        if (!empty($productPrice)) {
            $values = $request->except(['_token']);
            $valid = $this->validateInput($values, $productPrice);

            if ($valid['status'] === true) {
                $values['created_by'] = $request->user()->id;

                DB::beginTransaction();
                try {
                    $productPrice->delete();
                    ProductPrice::create($values);

                    session([
                        'message' => 'Bonus Produk berhasil disimpan.',
                        'messageClass' => 'success',
                    ]);

                    DB::commit();
                } catch (\Exception $e) {
                    DB::rollBack();
                    $responCode = 500;
                    $responText = $this->validationMessages('Telah terjadi kesalahan pada server. Silahkan coba lagi.' . (isLive() ? '' : ' ' . $e->getMessage()));
                }
            } else {
                $responCode = 400;
                $responText = $valid['message'];
            }
        } else {
            $responCode = 404;
            $responText = $this->validationMessages('Harga produk belum ditentukan.');
        }

        return response($responText, $responCode);
    }
}

resources/views/main/products/discount/delete.blade.php
<form class="modal-content" method="POST" action="{{ route('main.master.product.discount.destroy', ['product' => $product->id, 'mitraDiscount' => $data->id]) }}" id="myForm" data-alert-container="#alert-delete-container">
    <div class="modal-header py-2 px-3">
        <span class="fw-bold small">{{ $modalHeader }}</span>
        <button type="button" class="btn-close lh-1" data-bs-dismiss="modal" style="background: none; font-size:12px;">
            <i class="fa-solid fa-times"></i>
        </button>
    </div>
    <div class="modal-body">
        @csrf
        <div class="d-block" id="alert-delete-container"></div>
        <div class="text-center">
            Hapus diskon untuk produk <span class="fw-bold">{{ $product->name }}</span> yang jumlah minimal <span class="fw-bold">@formatNumber($data->min_qty, 0)</span>
        </div>
        <div class="text-center">???</div>
    </div>
    <div class="modal-footer py-1">
        <button type="submit" class="btn btn-sm btn-danger">
            <i class="fa-solid fa-trash me-1"></i>
            Hapus
        </button>
        <button type="button" class="btn btn-sm btn-warning" data-bs-dismiss="modal">
            <i class="fa-solid fa-undo me-1"></i>
            Batal
        </button>
    </div>
</form>

resources/views/main/products/discount/form.blade.php
@php
    $data = optional($data);
@endphp

<form class="modal-content" method="POST" action="{{ $postUrl }}" id="myForm" data-alert-container="#alert-dicount-container">
    <div class="modal-header py-2 px-3">
        <span class="fw-bold small">{{ $modalHeader }}</span>
        <button type="button" class="btn-close lh-1" data-bs-dismiss="modal" style="background: none; font-size:12px;">
            <i class="fa-solid fa-times"></i>
        </button>
    </div>
    <div class="modal-body">
        @csrf
        <input type="hidden" name="product_id" value="{{ $product->id }}">
        <input type="hidden" name="mitra_type" value="{{ MITRA_TYPE_AGENT }}">
        <div class="d-block" id="alert-dicount-container"></div>
        <div class="row g-2">
            <div class="col-12">
                <label class="d-block required">Zona</label>
                <select name="zone_id" class="form-select" autocomplete="off" required>
                    @foreach ($zones as $zone)
                        <option value="{{ $zone->id }}" @optionSelected($zone->id, $data->zone_id ?? $selectedZoneId)>{{ $zone->name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-12">
                <label class="d-block required">Kategori</label>
                <select name="discount_category" class="form-select" autocomplete="off" required>
                    @foreach (MITRA_DISCOUNT_CATEGORIES as $category_id => $category_name)
                        @php
                            if ($category_id == 0) continue;
                        @endphp
                        <option value="{{ $category_id }}" @optionSelected($category_id, $data->discount_category ?? 0)>{{ $category_name }}</option>
                    @endforeach
                </select>
            </div>
            <div class="col-12">
                <label class="d-block required">QTY</label>
                <input type="number" class="form-control" name="min_qty" value="{{ $data->min_qty ?? 0 }}" min="0" step="1" autocomplete="off" required>
            </div>
            <div class="col-12">
                <label class="d-block required">Diskon</label>
                <div class="input-group">
                    <label class="input-group-text">Rp</label>
                    <input type="number" class="form-control" name="discount" value="{{ $data->discount ?? 0 }}" min="0" step="100" autocomplete="off" required>
                </div>
            </div>
        </div>
    </div>
    <div class="modal-footer py-1">
        <button type="submit" class="btn btn-sm btn-primary">
            <i class="fa-solid fa-save me-1"></i>
            Simpan
        </button>
        <button type="button" class="btn btn-sm btn-warning" data-bs-dismiss="modal">
            <i class="fa-solid fa-undo me-1"></i>
            Batal
        </button>
    </div>
</form>

resources/views/main/products/discount/index.blade.php
@extends('layouts.app-main')

@section('content')
@include('partials.alert')
<div class="card mb-3">
    <div class="card-body p-2">
        <div class="row g-2">
            <div class="col-md-2 d-flex align-items-center justify-content-center">
                <img src="{{ $product->image_url }}" alt="{{ $product->name }}" style="max-width:100px;">
            </div>
            <div class="col-md-6 text-center text-md-start">
                <div class="fw-bold">{{ $product->name }}</div>
                <div>{{ $product->category_name }}</div>
                <div class="d-none d-md-block">{!! $product->notes ?? '' !!}</div>
            </div>
            <div class="col-md-4 d-flex align-items-center justify-content-center text-center">
                <div>
                    <div id="product-price" class="fw-bold fs-2"></div>
                    <div>Per - {{ $product->product_unit }}</div>
                </div>
            </div>
        </div>
    </div>
</div>

@foreach ($product->prices as $price)
    <input type="hidden" id="zone-{{ $price->zone_id }}" value="{{ $price->mitra_price }}">
@endforeach

<div class="mb-2" id="discount-filter">
    <div class="input-group input-group-sm w-auto">
        <label for="zona" class="input-group-text">Zona</label>
        <select id="zone-id" class="form-select pe-4" autocomplete="off">
            @foreach ($zones as $zone)
                <option value="{{ $zone->id }}" @optionSelected($zone->id, $currentZoneId)>{{ $zone->name }}</option>
            @endforeach
        </select>
    </div>
</div>

<table class="table table-sm table-nowrap table-striped table-hover" id="table">
    <thead class="bg-gradient-brighten bg-white small">
        <tr class="text-center">
            <th>QTY ({{ $product->product_unit }})</th>
            <th class="border-start">Diskon</th>
            <th class="border-start"></th>
        </tr>
    </thead>
    <tbody class="small"></tbody>
</table>

@php
    $canCreate = hasPermission('main.master.product.discount.create');
    $myDtButtons = [];
    $myDtButtons[] = [
        'class' => 'btn-href',
        'html' => 'Kembali',
        'data-href' => route('main.master.product.index'),
    ];
    if ($canCreate) {
        $myDtButtons[] = [
            'id' => 'btn-tambah',
            'html' => 'Tambah',
            'data-bs-toggle' => 'modal',
            'data-bs-target' => '#my-modal',
            'data-modal-url' => route('main.master.product.discount.create', ['product' => $product->id]),
        ];
    }
    $myDtButtons[] = [
        'id' => 'btn-refresh',
        'html' => '<i class="fa-solid fa-rotate"></i>',
        'title' => 'Refresh',
        'onclick' => "refreshTable();"
    ];
@endphp
@endsection

@push('includeContent')
    @include('partials.modals.modal', ['bsModalId' => 'my-modal', 'scrollable' => true])
@endpush

@push('vendorCSS')
<link rel="stylesheet" href="{{ asset('vendor/datatables/DataTables-1.11.4/css/dataTables.bootstrap5.min.css') }}">
<link rel="stylesheet" href="{{ asset('vendor/datatables/Buttons-2.2.2/css/buttons.dataTables.min.css') }}">
@endpush

@push('vendorJS')
<script src="{{ asset('vendor/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('vendor/datatables/DataTables-1.11.4/js/dataTables.bootstrap5.min.js') }}"></script>
<script src="{{ asset('vendor/jquery/jquery.number.min.js') }}"></script>
@endpush

@push('styles')
<style>
    .table.table-detail > tbody > tr > td,
    .table.table-detail > tfoot > tr > td {
        border: none;
    }
</style>
@endpush

@push('scripts')

@include('partials.datatable-custom', [
    'datatableButtons' => $myDtButtons,
    'datatableResponsive' => 'md',
])

<script>
    let table, select_zone;
    let create_url = '{{ route("main.master.product.discount.create", ["product" => $product->id]) }}';

    function formatCurrency(value)
    {
        return '<sup class="me-1 fw-normal">Rp</sup>' + $.number(value, 0, ',', '.');
    }

    function refreshTable()
    {
        $('#btn-tambah').data('modal-url', create_url + '?zone_id=' + select_zone.val());
        table.ajax.reload();
    }

    function fixClassRows()
    {
        const rows = $('#table > tbody > tr');
        $.each(rows, function(k, v) {
            const m = (k + 1) % 2;
            const r = $(v);
            if (m != 0) {
                r.removeClass('even').addClass('odd');
            } else {
                r.removeClass('odd').addClass('even');
            }
        });
    }

    $(function() {
        select_zone = $('#zone-id');

        table = $('#table').DataTable({
            dom: datatableDom,
            processing: true,
            serverSide: true,
            ajax: {
                url: '{{ route("main.master.product.discount.datatable", ["product" => $product->id]) }}',
                data: function(d) {
                    d.zone_id = select_zone.val();
                }
            },
            deferLoading: 50,
            info: false,
            lengthChange: false,
            searching: false,
            sort: false,
            paging: false,
            pagingType: datatablePagingType,
            lengthMenu: datatableLengMenu,
            language: datatableLanguange,
            buttons: datatableButtons,
            columns: [
                {data: 'min_qty', className: 'dt-body-center'},
                {data: 'discount', className: 'dt-body-right', render: function(data, type, row) {
                    return formatCurrency(data);
                }},
                {data: 'view', className: 'dt-body-center'},
            ],
            drawCallback: function (settings) {
                const api = this.api();
                const apiRows = api.rows({ page: 'current' });
                const rows = apiRows.nodes();
                let g1 = null;
                let total1 = {};

                apiRows.every(function ( rowIdx, tableLoop, rowLoop ) {
                    const data = this.data();
                    const row = $(rows).eq(rowIdx);

                    if (data.discount_category != g1) {
                        row.before('<tr class="group"><td colspan="3" class="fw-bold bg-primary text-light">' + data.discount_category_name + '</td></tr>');
                        
                        g1 = data.discount_category;
                    }
                });
            },
        }).on( 'draw.dt', function () {
            fixClassRows();
        });;

        customizeDatatable();
        
        const dtWrapper = $('#table_wrapper.dataTables_wrapper #buttons-2');
        dtWrapper.addClass('me-2').after($('#discount-filter'));
        
        select_zone.on('change', function(e) {
            const prc = $('#zone-' + $(this).val()).val();
            $('#product-price').html(formatCurrency(prc));
            refreshTable();
        }).change();
    });
</script>
@endpush